version: '3.1'

volumes:
  mongo_data:

services:
  app:
    build: ./app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
    - ./app:/app/backend
    ports:
    - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "pelocho"
      MONGO_INITDB_ROOT_PASSWORD: "pel8"
    volumes:
    - mongo_data:/data/db
    ports:
    - "27017:27017"
