fastapi:
  debug: true

api:
  versions:
    current: v1
    supported:
    deprecated:
    unsupported:

databases:
  default:
    ENGINE: 'mongodb'
    DRIVER: 'motor'
    NAME: 'app_db'
    USER: 'pelocho'
    PASSWORD: 'pel8'
    HOST: 'mongo'
    PORT: '27017'